client: Support PKCS#11 3.0
p11-glue/p11-kit pull request #486
Opened 2023-04-09 02:14 UTC by ueno

This exports `C_GetInterfaceList` and `C_GetInterface` from the client module.

2023-04-11 11:05 UTC, ZoltanFridrich requested changes
Looks good, but I have some comments.

2023-04-11 11:05 UTC, ZoltanFridrich commented on p11-kit/client.c
> +	*interface = &state->wrapped;
I would put an assert on interface not being NULL

2023-04-11 11:05 UTC, ZoltanFridrich commented on p11-kit/proxy.c
> +	*interface = &state->wrapped;
assert that interface is not NULL

2023-04-11 11:59 UTC, ueno commented on p11-kit/client.c
> +		pVersion = NULL;
Indeed, that's a good point; I've removed the special case and made `get_interface_inlock` always expects non-NULL `version`.

2023-06-28 06:05 UTC, ZoltanFridrich approved these changes

2023-06-28 06:05 UTC, merged