p11-kit tool: make "no matching object/token" error user friendly
p11-glue/p11-kit pull request #575
Opened 2023-09-22 09:15 UTC by ZoltanFridrich

- don't check slot == 0 as 0 is a valid slot ID
-  make the error message human friendly when no token/object is matched

Closes #574

2023-09-22 09:54 UTC, ueno commented on p11-kit/add-profile.c
> +	if (p11_kit_iter_next (iter) != CKR_OK) {
I guess we could special case `CKR_CANCEL` in this case, as there might be other errors?

2023-09-23 11:08 UTC, ueno requested changes
And of course, please add a test for the issues this PR is fixing.

2023-09-26 11:19 UTC, ueno commented on p11-kit/test-objects.sh
> +	fi
```suggestion
        assert_contains err.out "no matching token"
```

2023-09-26 11:19 UTC, ueno commented on p11-kit/test-objects.sh
> +	fi
Same suggestion above, using `assert_contains`.

2023-09-26 11:19 UTC, ueno commented on p11-kit/test-profiles.sh
> +	fi
Same suggestion above, using `assert_contains`.

2023-09-26 11:25 UTC, ZoltanFridrich commented on p11-kit/test-objects.sh
> +	fi
that looks nice, thanks!

2023-09-26 12:19 UTC, merged