token: sort paths for reproducible extract
p11-glue/p11-kit pull request #656
Opened 2024-08-28 13:26 UTC by katexochen

There is no defined order in which readdir will return the entries of a directory. In practice, order can depend on inode number or similar. If we run p11-kit on different files systems with similar directory structure but different inode order the output of extract can change.

To get a stable and reproducible output, sort the paths returned by readdir before extracting.

2024-08-28 15:02 UTC, ZoltanFridrich commented on trust/token.c
> +	paths = p11_array_new (NULL);
This should have an error guard as this can return NULL.

2024-08-28 15:03 UTC, ZoltanFridrich commented on trust/token.c
> +	char **p1 = (char **)one;
Can p1 and p2 be const?

2024-08-28 15:15 UTC, ZoltanFridrich commented on trust/token.c
> +			free (path);
A simple `return_val_if_fail` will suffice as `p11_array_push` will only fail in case of OOM in which case the program dies anyway.

2024-08-28 15:18 UTC, ZoltanFridrich commented on trust/token.c
> +    for (int i = 0; i < paths->num; i++) {
Please move the declaration of `i` at the start of the function.

2024-08-28 15:20 UTC, ZoltanFridrich commented on trust/token.c
> +    closedir(dir);
Formatting needs fixing. You are mixing TABs and spaces + put space between function name and brackets.

2024-08-28 15:22 UTC, ZoltanFridrich requested changes
Thank you for your contribution!
The change looks good overall, but I would like to see some things fixed before I can merge it.

2024-08-29 07:20 UTC, katexochen commented
> The change looks good overall, but I would like to see some things fixed before I can merge it.

Thanks for your feedback, I tried to incorporate the requested changes. Let me know if I overlooked something. :)

2024-08-30 12:33 UTC, ZoltanFridrich approved these changes
Looks good!

2024-08-30 12:54 UTC, ZoltanFridrich commented
@katexochen please rebase it to master so I can merge.

2024-08-30 13:12 UTC, merged